/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;
import Model.Servico;
/**
 *
 * @author Aluno
 */
public class ServicoView extends javax.swing.JFrame {

    /**
     * Creates new form ServicoView
     */
    public ServicoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPServico = new javax.swing.JTabbedPane();
        jPMensalista = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jbLimparMensa = new javax.swing.JButton();
        jbGravarMensa = new javax.swing.JButton();
        jbImprimirMensa = new javax.swing.JButton();
        jbVoltarMens = new javax.swing.JButton();
        jbAlterarM = new javax.swing.JButton();
        jbExcluirM = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jcbLimpezaM = new javax.swing.JCheckBox();
        jcbPolimentoM = new javax.swing.JCheckBox();
        jtPlacaM = new javax.swing.JTextField();
        jtMarcaM = new javax.swing.JTextField();
        jtCorM = new javax.swing.JTextField();
        jtDtInicio = new javax.swing.JTextField();
        jtDtFim = new javax.swing.JTextField();
        jbBuscarM = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jtVagaM = new javax.swing.JTextField();
        jPAvulso = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbLimpeza = new javax.swing.JCheckBox();
        jcbPolimento = new javax.swing.JCheckBox();
        jtHrEntrada = new javax.swing.JTextField();
        jtHrSaida = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jbLimpar = new javax.swing.JButton();
        jbGravar = new javax.swing.JButton();
        jbVoltar = new javax.swing.JButton();
        jbImprimir = new javax.swing.JButton();
        jbAlterar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtPlaca = new javax.swing.JTextField();
        jtMarca = new javax.swing.JTextField();
        jtCor = new javax.swing.JTextField();
        jCBoxTamanho = new javax.swing.JComboBox<>();
        jbBuscar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jtVaga = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmMensalista = new javax.swing.JMenu();
        jmCadastrar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbLimparMensa.setText("Limpar");
        jbLimparMensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparMensaActionPerformed(evt);
            }
        });

        jbGravarMensa.setText("Gravar");
        jbGravarMensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGravarMensaActionPerformed(evt);
            }
        });

        jbImprimirMensa.setText("Imprimir");
        jbImprimirMensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbImprimirMensaActionPerformed(evt);
            }
        });

        jbVoltarMens.setText("Voltar");
        jbVoltarMens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVoltarMensActionPerformed(evt);
            }
        });

        jbAlterarM.setText("Alterar");
        jbAlterarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarMActionPerformed(evt);
            }
        });

        jbExcluirM.setText("Excluir");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbLimparMensa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbGravarMensa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbImprimirMensa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbVoltarMens)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbAlterarM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbExcluirM)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbLimparMensa)
                    .addComponent(jbGravarMensa)
                    .addComponent(jbImprimirMensa)
                    .addComponent(jbVoltarMens)
                    .addComponent(jbAlterarM)
                    .addComponent(jbExcluirM))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jLabel7.setText("Placa:");

        jLabel8.setText("Marca:");

        jLabel9.setText("Cor:");

        jLabel10.setText("Data de Início:");

        jLabel11.setText("Data de Encerramento:");

        jcbLimpezaM.setText("Limpeza");

        jcbPolimentoM.setText("Polimento");

        jbBuscarM.setText("Buscar");
        jbBuscarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarMActionPerformed(evt);
            }
        });

        jLabel13.setText("Vaga:");

        javax.swing.GroupLayout jPMensalistaLayout = new javax.swing.GroupLayout(jPMensalista);
        jPMensalista.setLayout(jPMensalistaLayout);
        jPMensalistaLayout.setHorizontalGroup(
            jPMensalistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPMensalistaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPMensalistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPMensalistaLayout.createSequentialGroup()
                        .addComponent(jtPlacaM, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbBuscarM)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPMensalistaLayout.createSequentialGroup()
                        .addGroup(jPMensalistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPMensalistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jtDtInicio, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtCorM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                            .addGroup(jPMensalistaLayout.createSequentialGroup()
                                .addComponent(jcbLimpezaM)
                                .addGap(48, 48, 48)
                                .addComponent(jcbPolimentoM))
                            .addComponent(jLabel7)
                            .addComponent(jLabel10))
                        .addGap(33, 33, 33)
                        .addGroup(jPMensalistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPMensalistaLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPMensalistaLayout.createSequentialGroup()
                                .addGroup(jPMensalistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPMensalistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel8)
                                        .addComponent(jtMarcaM, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                        .addComponent(jLabel13)
                                        .addComponent(jtVagaM))
                                    .addComponent(jtDtFim, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        jPMensalistaLayout.setVerticalGroup(
            jPMensalistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPMensalistaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPMensalistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPMensalistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtPlacaM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscarM)
                    .addComponent(jtVagaM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPMensalistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addGap(4, 4, 4)
                .addGroup(jPMensalistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtCorM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtMarcaM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPMensalistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(4, 4, 4)
                .addGroup(jPMensalistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtDtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtDtFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPMensalistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbLimpezaM)
                    .addComponent(jcbPolimentoM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPServico.addTab("Mensalista", jPMensalista);

        jLabel1.setText("Hora de Entrada:");

        jLabel2.setText("Hora de Saída:");

        jcbLimpeza.setText("Limpeza");

        jcbPolimento.setText("Polimento");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jbGravar.setText("Gravar");
        jbGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGravarActionPerformed(evt);
            }
        });

        jbVoltar.setText("Voltar");
        jbVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVoltarActionPerformed(evt);
            }
        });

        jbImprimir.setText("Imprimir");
        jbImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbImprimirActionPerformed(evt);
            }
        });

        jbAlterar.setText("Alterar");

        jbExcluir.setText("Excluir");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbGravar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbImprimir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbExcluir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbLimpar)
                    .addComponent(jbGravar)
                    .addComponent(jbVoltar)
                    .addComponent(jbImprimir)
                    .addComponent(jbAlterar)
                    .addComponent(jbExcluir))
                .addContainerGap())
        );

        jLabel3.setText("Placa:");

        jLabel4.setText("Modelo:");

        jLabel5.setText("Cor: ");

        jLabel6.setText("Tamanho:");

        jCBoxTamanho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCBoxTamanho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBoxTamanhoActionPerformed(evt);
            }
        });

        jbBuscar.setText("Buscar");

        jLabel12.setText("Vaga:");

        javax.swing.GroupLayout jPAvulsoLayout = new javax.swing.GroupLayout(jPAvulso);
        jPAvulso.setLayout(jPAvulsoLayout);
        jPAvulsoLayout.setHorizontalGroup(
            jPAvulsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPAvulsoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPAvulsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtCor, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addGroup(jPAvulsoLayout.createSequentialGroup()
                        .addGroup(jPAvulsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPAvulsoLayout.createSequentialGroup()
                                .addComponent(jcbLimpeza)
                                .addGap(46, 46, 46)
                                .addComponent(jcbPolimento))
                            .addComponent(jLabel4)
                            .addComponent(jtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addGroup(jPAvulsoLayout.createSequentialGroup()
                                .addComponent(jtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbBuscar)))
                        .addGap(42, 42, 42)
                        .addGroup(jPAvulsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12)
                            .addComponent(jLabel2)
                            .addComponent(jtHrEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(jLabel6)
                            .addComponent(jCBoxTamanho, 0, 146, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(jtHrSaida, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(jtVaga))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPAvulsoLayout.setVerticalGroup(
            jPAvulsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAvulsoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPAvulsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPAvulsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscar)
                    .addComponent(jtVaga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPAvulsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGroup(jPAvulsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPAvulsoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPAvulsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbLimpeza)
                            .addComponent(jcbPolimento))
                        .addGap(18, 18, 18))
                    .addGroup(jPAvulsoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCBoxTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPAvulsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPAvulsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtHrEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtHrSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPServico.addTab("Avulso", jPAvulso);

        jmMensalista.setText("Cliente");

        jmCadastrar.setText("Cadastrar");
        jmCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadastrarActionPerformed(evt);
            }
        });
        jmMensalista.add(jmCadastrar);

        jMenuBar1.add(jmMensalista);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPServico)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPServico))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadastrarActionPerformed
       ClienteView m = new ClienteView();
       m.setVisible(true);
    }//GEN-LAST:event_jmCadastrarActionPerformed

    private void jCBoxTamanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBoxTamanhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBoxTamanhoActionPerformed

    private void jbVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVoltarActionPerformed
        MenuView mn = new MenuView();
        mn.setVisible(true);
    }//GEN-LAST:event_jbVoltarActionPerformed

    private void jbGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGravarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbGravarActionPerformed

    private void jbImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbImprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbImprimirActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        //jcbLimpeza.setText("");
        //jcbPolimento.setText("");
        jtPlaca.setText("");
        jtMarca.setText("");
        jtCor.setText("");
        jtHrEntrada.setText("");
        jtHrSaida.setText("");
        //jCBoxTamanho.setToolTipText("");
        
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jbLimparMensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparMensaActionPerformed
        jtPlacaM.setText("");
        jtMarcaM.setText("");
        jtCorM.setText("");
        jtDtInicio.setText("");
        jtDtFim.setText("");
    }//GEN-LAST:event_jbLimparMensaActionPerformed

    private void jbGravarMensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGravarMensaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbGravarMensaActionPerformed

    private void jbImprimirMensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbImprimirMensaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbImprimirMensaActionPerformed

    private void jbVoltarMensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVoltarMensActionPerformed
         MenuView mn = new MenuView();
         mn.setVisible(true);
    }//GEN-LAST:event_jbVoltarMensActionPerformed

    private void jbBuscarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbBuscarMActionPerformed

    private void jbAlterarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbAlterarMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServicoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServicoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServicoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServicoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServicoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCBoxTamanho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPAvulso;
    private javax.swing.JPanel jPMensalista;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPServico;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbAlterarM;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbBuscarM;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbExcluirM;
    private javax.swing.JButton jbGravar;
    private javax.swing.JButton jbGravarMensa;
    private javax.swing.JButton jbImprimir;
    private javax.swing.JButton jbImprimirMensa;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbLimparMensa;
    private javax.swing.JButton jbVoltar;
    private javax.swing.JButton jbVoltarMens;
    private javax.swing.JCheckBox jcbLimpeza;
    private javax.swing.JCheckBox jcbLimpezaM;
    private javax.swing.JCheckBox jcbPolimento;
    private javax.swing.JCheckBox jcbPolimentoM;
    private javax.swing.JMenuItem jmCadastrar;
    private javax.swing.JMenu jmMensalista;
    private javax.swing.JTextField jtCor;
    private javax.swing.JTextField jtCorM;
    private javax.swing.JTextField jtDtFim;
    private javax.swing.JTextField jtDtInicio;
    private javax.swing.JTextField jtHrEntrada;
    private javax.swing.JTextField jtHrSaida;
    private javax.swing.JTextField jtMarca;
    private javax.swing.JTextField jtMarcaM;
    private javax.swing.JTextField jtPlaca;
    private javax.swing.JTextField jtPlacaM;
    private javax.swing.JTextField jtVaga;
    private javax.swing.JTextField jtVagaM;
    // End of variables declaration//GEN-END:variables
}
